spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: library

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog