spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: library

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
